### ISSUE TITLE
SSL and replica settings?

### ISSUE THREAD

**Issue by 0xicl33n** [zhaoyi0113/mongodb-runner#1]
I have this in my workspace settings
```
		"mongoRunner": {
			"connection": {
				"url": "'mongodb://host1:port,host2:port,host3:port",
				"activeOnStartUp": true,
				"username": "user",
				"password" : "password",
				"database" : "db",
				"replicaSet": "rs",
				"ssl" : "true",
				"ssl_ca_certs" : "c:\\path\\to\\db.pem",
				"authsource": "admin",

			}
```

And i am unable to connect, is this the correct method i would use to use ssl and a replica set or am i doing something wrong? I tried with just a uri but that didnt work either

**Comment by zhaoyi0113** [comment]
Thanks for reporting this issue. I have fixed it in my local but I am facing a trouble to publish a new version in VSCode. I will let you know when a new version is ready.

**Comment by zhaoyi0113** [comment]
Please update the extension to the latest version and configure ssl as below. All other mongo connection related options can be configured in the `options` object. Please let me know whether it works for you.

```
"mongoRunner": {
        "connection": {
            "url": "mongodb://localhost:27017",
            "activeOnStartUp": true,
            "user": "username",
            "options": {
                "ssl": true
            }
        }
    }
```

**Comment by zhaoyi0113** [comment]
@0xicl33n Could you let me know whether it works for you?
