### ISSUE TITLE
user is not required

### ISSUE THREAD

**Issue by xzdm** [zhaoyi0113/mongodb-runner#10]
delete "user" and try again when you get "Failed to connect MongoDB."

**Comment by zhaoyi0113** [comment]
Mongodb Running is using the connection from settings. You can configure the right user name in the configuration after you delete that user. If you allow anonymous login, just delete `user` from the configuration.

**Comment by xzdm** [comment]
Thank you for your reply. And i will very appreciate if you can put it in ReadMe.

**Comment by zhaoyi0113** [comment]
@xzdm It is listed in https://github.com/zhaoyi0113/mongodb-runner#extension-settings
