### ISSUE TITLE
Installed in Visual Studio Code but how to connect?

### ISSUE THREAD

**Issue by mikepoz59** [zhaoyi0113/mongodb-runner#107]
I installed the plugin, and have been struggling with how to configure the plugin to actually connect to the Mongo DB.

Readme documentation doesn't help.  Any assistance would be greatly appreciated, maybe a wiki page with steps?

Kind Regards,
Mike Poz

**Comment by zhaoyi0113** [comment]
Please follow this configuration for set it up: https://github.com/zhaoyi0113/mongodb-runner#extension-settings.
If it doesn't work, can you please send me your configuration and the Mongodb version you are using.
