### ISSUE TITLE
db.getCollection() is not a function

### ISSUE THREAD

**Issue by zoujialing125** [zhaoyi0113/mongodb-runner#121]
The extension cannot execute the function db.getCollection(), as our collection name contains special chars we must must use getCollection to get doc correctly. Is there any solution to fix that problem?

but it's wired that if we don't put any filter information in find(), it works correctly.

**Comment by zhaoyi0113** [comment]
Hi @zoujialing125 , could you provide me the command you run which causing the issue? And your collection name, and the `find()` command which runs correctly?

**Comment by zoujialing125** [comment]
Hi @zhaoyi0113 , thanks for your swift reply. I think I made a mistake to use collection().find() with wrong collection name, so i cannot get expected result. My collection name is xxx-xxx-xxx, it's actually worked very well, no need getCollection function at all.
