### ISSUE TITLE
How to connect to mlab?

### ISSUE THREAD

**Issue by mojaray2k** [zhaoyi0113/mongodb-runner#2]
I was trying to connect to [MLab](https://mlab.com/home) but I could not.

Here is an example connection on [ How would someone connect their MLAB mongodb database to robomongo when MLAB only provides string URI's [duplicate]](https://stackoverflow.com/questions/44422694/how-would-someone-connect-their-mlab-mongodb-database-to-robomongo-when-mlab-onl)

Here is a example connection string
`mongodb://<dbuser>:<dbpassword>@ds111111.mlab.com:55191/<dbName>`

**Comment by zhaoyi0113** [comment]
Thanks for your feedback. Could you let me know whether I can install an environment locally to reproduce this issue? Or it would be great if you know there is a docker image I can download.

**Comment by zhaoyi0113** [comment]
I tried to create a database on MLab and I couldn't even connect to it through mongo shell. I am sure about how MLab accept remote connections. 
In general, if you put user credential on the connection URL, you don't need to specify the user name separate.

**Comment by zhaoyi0113** [comment]
@mojaray2k  Could you let me know how you connect to MLab through mongo shell? I wonder whether I have the correct setting or not.

**Comment by zhaoyi0113** [comment]
fixed in the latest version
