### ISSUE TITLE
Cannot execute after saving editor file

### ISSUE THREAD

**Issue by ericbynum** [zhaoyi0113/mongodb-runner#32]
Upon saving an Untitled MongoRunner Editor (.mr extension), the link to "Execute" disappears and the play (Execute All Commands) and clear (Clear Output) buttons no longer work.

VSCode v1.33.1
MongoRunner v0.5.6

**Comment by zhaoyi0113** [comment]
Thanks reporting this issue, fixed in the version v0.5.7.

**Comment by ericbynum** [comment]
Verified this has been fixed. Thanks for the quick turnaround! Awesome extension btw.
