### ISSUE TITLE
failed to query with ObjectId

### ISSUE THREAD

**Issue by VictorSu000** [zhaoyi0113/mongodb-runner#33]
I tried the following queries with ObjectId, but failed. What's the correct way?

```javascript
db.collection('classes').find().limit(1)
db.collection('classes').find({
    "_id": "ObjectId(5cadeef194eccdabd43df553)"
})
db.collection('classes').find({
    "_id": "ObjectId('5cadeef194eccdabd43df553')"
})
```

results:

```javascript
// MongoRunner> db.collection('classes').find().limit(1).toArray()
[
    {
        "_id": "5cadeef194eccdabd43df553"
    }
]
// MongoRunner> db.collection('classes').find({ '_id': 'ObjectId(5cadeef194eccdabd43df553)' }).limit(20).toArray()
[]
// MongoRunner> db.collection('classes').find({ '_id': 'ObjectId(\'5cadeef194eccdabd43df553\')' }).limit(20).toArray()
[]

// Here the last two queries failed. I can't get the document.
```

Did I use ObjectId correctly? Thanks for your help.

**Comment by zhaoyi0113** [comment]
You will see how to use object id if you look at the readme. I take a screenshot as below for your reference.

![image](https://user-images.githubusercontent.com/3355579/56940492-1d9f9a00-6b52-11e9-9436-6187b0d10b42.png)

**Comment by VictorSu000** [comment]
I did see that. So I tried to run this

```javascript
db.collection('classes').find({
    "_id": "ObjectId(5cadeef194eccdabd43df553)"
})
```

But you can read my results. That query got nothing. So I wonder whether I misunderstood the README.

This ObjectId exists in my database.  ```db.collection('classes').find().limit(1) ``` can find it.

**Comment by zhaoyi0113** [comment]
Thanks for reporting the issue. It was probably broken when I upgraded mongodb nodejs driver. I give a fix for that. Please upgrade to Mongodb runner v0.5.8 and try to query objectIb by: 
```
db.collection('classes').find({
    "_id": new ObjectID("5cadeef194eccdabd43df553")
})
```

Please let me know you have any trouble on using it.

**Comment by VictorSu000** [comment]
It works. Plenty of thanks!
