### ISSUE TITLE
Unknown configuration setting/extension not working or recognized

### ISSUE THREAD

**Issue by joeyfigaro** [zhaoyi0113/mongodb-runner#4]
![](https://d3vv6lp55qjaqc.cloudfront.net/items/0x1n291E3t3j1Y390Q3T/Image%202018-09-15%20at%209.05.33%20AM.png?X-CloudApp-Visitor-Id=1332463&v=70ad48b5)

versions tested: `1.28.0-insider` and `1.26.1`

Fresh install, key isn't recognized in workspace or user settings.

**Comment by zhaoyi0113** [comment]
@joeyfigaro  Thanks for choosing MongoDB Runner. I have fixed the issue. Could you please update to the latest version? let me know if you still have this issue.

**Comment by zhaoyi0113** [comment]
fixed in the latest version
