### ISSUE TITLE
simple query by _id

### ISSUE THREAD

**Issue by mustafa-kahraman** [zhaoyi0113/mongodb-runner#5]
How can I query a document by _id?

I have tried this versions to query, but no result...
```
{"_id": "1234" }
{ "_id" : ObjectId("1234") }
```

**Comment by zhaoyi0113** [comment]
Thanks for reporting this issue. Please update the latest version of `mongodb-runner` and you should be able to query object id by `{ "_id" : "ObjectId(1234)" }`

**Comment by zhaoyi0113** [comment]
fixed in the latest version
